#use wildcard "*" to expose all the endpoints
#can also expose individual endpoints with a comma-delimited list
spring.application.name=BerlinApp

#below line is for individual exposing of endpoints
#management.endpoints.web.exposure.include = health,info

#below line is for exposing of all endpoints
management.endpoints.web.exposure.include = *

#Excude individual endpoints with comma-delimited list
management.endpoints.web.exposure.exclude = health,info

management.info.env.enabled = true
#once we set these two items up then this will expose the /info endpoint
#bydefault info is empty and all the attribute of actuator starts with prefix "/actuator"
info.app.name = berlin's super cool app
info.app.description = A qwaazzy app, created by berlin
info.app.version = 1.0.0
info.app.theOGcreator = Berlin